Repository kiwix/kiwix-android, pull requests merged in 2019-08, with the labels that each got.

#1345 Add only distinct zims to local database
  app/src/main/java/org/kiwix/kiwixmobile/database/newdb/dao/NewBookDao.kt
Labels: bug

#1353 Fix #1352 Download button is fixed to right even for RTL scripts
  app/src/main/res/layout/content_main.xml
Labels: UI

#1276 GSoC 2019 Deliverable: Local File Transfer
  app/build.gradle
  app/src/androidTestKiwix/resources/testzim.zim
  app/src/customexample/res/mipmap-mdpi/kiwix_icon.png
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/kiwix/kiwixmobile/data/local/entity/LibraryDataSource.java
  app/src/main/java/org/kiwix/kiwixmobile/di/components/ActivityComponent.kt
  app/src/main/java/org/kiwix/kiwixmobile/di/modules/ApplicationModule.java
  app/src/main/java/org/kiwix/kiwixmobile/utils/KiwixDialog.kt
  app/src/main/java/org/kiwix/kiwixmobile/zim_manager/ZimManageActivity.kt
  app/src/main/java/org/kiwix/kiwixmobile/zim_manager/local_file_transfer/FileItem.java
  app/src/main/java/org/kiwix/kiwixmobile/zim_manager/local_file_transfer/FileListAdapter.java
  app/src/main/java/org/kiwix/kiwixmobile/zim_manager/local_file_transfer/KiwixWifiP2pBroadcastReceiver.java
  app/src/main/java/org/kiwix/kiwixmobile/zim_manager/local_file_transfer/LocalFileTransferActivity.java
  app/src/main/java/org/kiwix/kiwixmobile/zim_manager/local_file_transfer/PeerGroupHandshakeAsyncTask.java
  app/src/main/java/org/kiwix/kiwixmobile/zim_manager/local_file_transfer/ReceiverDeviceAsyncTask.java
  app/src/main/java/org/kiwix/kiwixmobile/zim_manager/local_file_transfer/SenderDeviceAsyncTask.java
  app/src/main/java/org/kiwix/kiwixmobile/zim_manager/local_file_transfer/WifiDirectManager.java
  app/src/main/java/org/kiwix/kiwixmobile/zim_manager/local_file_transfer/WifiPeerListAdapter.java
  app/src/main/res/drawable-xxhdpi/ic_action_back.png
  app/src/main/res/drawable-xxhdpi/ic_action_delete.png
  app/src/main/res/drawable-xxhdpi/ic_action_forward.png
  app/src/main/res/drawable-xxhdpi/ic_action_plus.png
  app/src/main/res/drawable/ic_baseline_check_24px.xml
  app/src/main/res/drawable/ic_baseline_error_24px.xml
  app/src/main/res/drawable/ic_baseline_mobile_screen_share_24px.xml
  app/src/main/res/drawable/ic_baseline_wait_24px.xml
  app/src/main/res/drawable/ic_close_white_24dp.xml
  app/src/main/res/drawable/list_bg.xml
  app/src/main/res/drawable/list_bg_light.xml
  app/src/main/res/layout/activity_local_file_transfer.xml
  app/src/main/res/layout/item_transfer_list.xml
  app/src/main/res/layout/library_item.xml
  app/src/main/res/layout/progress_bar.xml
  app/src/main/res/layout/row_peer_device.xml
  app/src/main/res/menu/menu_zim_manager.xml
  app/src/main/res/menu/wifi_file_share_items.xml
  app/src/main/res/values/strings.xml
  create-signed-android-release.sh
  gradlew
  install-kiwix-on-device.sh
  make-screenshot.sh
  testdroid.py
  update-play-store.py
  upload-apk.py
Labels: gsoc 2019

#1384 Fix tabs orientation in tabs overview
  app/src/main/java/org/kiwix/kiwixmobile/main/MainActivity.java
  app/src/main/java/org/kiwix/kiwixmobile/main/TabsAdapter.java
  app/src/main/java/org/kiwix/kiwixmobile/utils/ImageUtils.java
  app/src/main/java/org/kiwix/kiwixmobile/utils/ImageUtils.kt
Labels: UI, bug
